#!/bin/sh
#----------------------------------------------------------------#
#   __  __           _ ____             _            _   _ ___   #
#  |  \/  | ___   __| |  _ \ ___  _   _| |_ ___ _ __| | | |_ _|  #
#  | |\/| |/ _ \ / _` | |_) / _ \| | | | __/ _ \ '__| | | || |   #
#  | |  | | (_) | (_| |  _ < (_) | |_| | ||  __/ |  | |_| || |   #
#  |_|  |_|\___/ \__,_|_| \_\___/ \__,_|\__\___|_|   \___/|___|  #
#----------------------------------------------------------------#

# Author:       kstamand
# Date:         2025-11-01
# Synopsis:     Hide select AsusWRT UI menuss 
# Description:  Installs/uninstals/modifies the list of "menus" that show in the browser when you go to the routers default webpage
# Reference:    This script is based on Asuswrt-merlin third party addon api
#+      https://github.com/RMerl/asuswrt-merlin/wiki/Addons-API/90b49e443b8ce64e82c0970237199deff46869f5
# Documentation: https://github.com/kstamand/HideUIMenus
# Credits:      Code in this script modeled after FlexQoS (Dave14305) and SpdMerlin (Jack Yaz)
#----------------------------------------------------------------------------------------------------#

# AsusWRT Merlin Addon API helper functions
source /usr/sbin/helper.sh

### Start of Script Variables
readonly SCRIPT_NAME="hideuimenus"
readonly SCRIPT_VERSION="v1.0.0"
readonly scriptVersRegExp="v[0-9]{1,2}([.][0-9]{1,2})([.][0-9]{1,2})"
readonly SCRIPT_NAME_DISPLAY="ModRouterUI"
readonly GIT_URL="https://raw.githubusercontent.com/kstamand/modrouterui/master"
readonly ADDON_DIR="/jffs/addons"
readonly SCRIPT_NAME_DIR="${ADDON_DIR}/modrouterui"
readonly SCRIPT_INSTALL_PATH="${SCRIPT_NAME_DIR}/${SCRIPT_NAME}"
readonly HIDEMENUS_FILE_PATH="${SCRIPT_NAME_DIR}/hide_menus_list"
readonly DEFAULTMENUS_FILE_PATH="${SCRIPT_NAME_DIR}/default_menu_list"
readonly LOCK_FILE="/tmp/addonwebui.lock" # lock file to avoid conflicts with other custom WebUI addons
readonly SETTINGS_FILE="/jffs/addons/custom_settings.txt"
readonly FILTER_MENUS_LIST="!/filtering|Split|Index|NewDashboard|APP/" # filter out router UI menu lines (INDEX: Menu_xxx) that have __HIDE__ in the URL
readonly MENUTREE_FILE="/tmp/menuTree.js" # Router file containing the information that controls what is displayed in Router UI

RED_TEXT='\033[31m'
GREEN_TEXT='\033[32m'
YELLOW_TEXT='\033[33m'
MAGENTA_TEXT='\033[35m'
CYAN_TEXT='\033[36m'
RESET='\033[0m'
### End of Script Variables

# -x is a flag to show verbose script output for debugging purposes only
Debug(){
    clear
    set -x
    Yellow "Debugging enabled ..."
}

Logmsg() {
    # Parameter options - $1 = message
    if [ "$#" = "0" ]; then #if no parameters passed, then just return
        return
    fi
    logger -t "${SCRIPT_NAME_DISPLAY}" "$*" # display any/all parameters passed
} # end of Logmsg

Red() {
    printf -- '\033[1;31m%s\033[0m\n' "${1}"
}

Green() {
    printf -- '\033[1;32m%s\033[0m\n' "${1}"
}

Yellow() {
    printf -- '\033[1;33m%s\033[0m\n' "${1}"
}

Magenta() {
    printf -- '\033[1;35m%s\033[0m\n' "${1}"
}

Cyan() {
    printf -- '\033[1;36m%s\033[0m\n' "${1}"
}

Scriptinfo() {
    # Version header used in interactive sessions
    [ "${mode}" = "interactive" ] || return
    printf "\n"
    Green "${SCRIPT_NAME_DISPLAY} ${SCRIPT_VERSION}"
    printf "\n"
} # end of Scriptinfo ()

About() {
    Scriptinfo
    echo -e "${CYAN_TEXT}"
    cat <<EOF
License
${SCRIPT_NAME_DISPLAY} is free to use under the GNU General Public License, version 3 (GPL-3.0).
https://opensource.org/licenses/GPL-3.0

For discussion visit this thread:
https://www.snbforums.com/forums/asuswrt-merlin-addons.60/?prefix_id=8
https://github.com/kstamand/HideUIMenus (Source Code)

About
Script maintains a Custom Webpage for selecting, running, and displaying script results
Reason - for those wishing to do as much as they can in the Router WebUI and avoid SSH for simple / informational commands
EOF
echo -e "${RESET}"
} # end of about() information

Show_Help() {
    echo -e "${CYAN_TEXT}"
    cat <<EOF
This script wiill read the contents of the file "hidemenus", located at /jffs/addons/HideUIMenus, for the list of router menus to hide. 

Edit the "hidemenus" file and add one line for each menu you DO NOT want to be visible in the router UI (e.g., you never use them).

Below is the list of valid menu names to use:
EOF
# don't display any menu_xxxx that have __HIDE__ in URL line as an option
echo -e "${GREEN_TEXT}"
grep index: /www/require/modules/menuTree.js | cut -d ' ' -f2- | sed 's/[",]//g' | awk "${FILTER_MENUS_LIST}"
echo -e "${RESET}"
grep index: /www/require/modules/menuTree.js | cut -d ' ' -f2- | sed 's/[",]//g' | awk "${FILTER_MENUS_LIST}" > "${DEFAULTMENUS_FILE_PATH}"
}

Press_Enter(){
    [ "${mode}" = "interactive" ] || return
    printf "\n"
    while true; do
        printf "Press enter to continue..."
        read -r "key"
        case "${key}" in
            *)
                break
            ;;
        esac
    done
    return 0
} # end of Press_Enter()

Check_Firmware() {
    Green "   - Checking firmware support"
    if ! nvram get rc_support | grep -q am_addons; then
        Red "${SCRIPT_NAME_DISPLAY} requires ASUSWRT-Merlin Addon API support. Installation aborted."
        return 1
    fi
    if [ "$(nvram get jffs2_scripts)" != "1" ]; then
        Red "   - Enable JFFS custom scripts and configs is not enabled. Please enable it in the GUI. Aborting installation."
        return 1
    fi
} # end of Check_Firmware()

Download_File() {
    # Parameter options: $1 = file name to download, $2 = full path + filename to download to
    # Download file from Github once to a temp location. If the same as the destination file, don't replace.
    # Otherwise move it from the temp location to the destination.
    if curl -fsL --retry 3 --connect-timeout 3 "${GIT_URL}/${1}" -o "/tmp/${1}"; then
        if [ "$(md5sum "/tmp/${1}" | awk '{print $1}')" != "$(md5sum "${2}" 2>/dev/null | awk '{print $1}')" ]; then
            mv -f "/tmp/${1}" "${2}"
            Green "   - Installed $(basename "${1}")"
        else
            Yellow "  File $(basename "${2}") is already up-to-date"
            rm -f "/tmp/${1}" 2>/dev/null
        fi
    else
        Red "   [ERROR] Install $(basename "${1}") failed"
        exit 5
    fi
} # end of Download_File()

Add_Startup(){
    # Parameters: $1 - install or uninstall
    case $1 in
        'install')
            Green "   - Inserting ${SCRIPT_INSTALL_PATH} services-start line"
            # check if a services-start file exists and process as follows
			if [ -f /jffs/scripts/services-start ]; then
				STARTUPLINECOUNT=$(grep -c "${SCRIPT_INSTALL_PATH}" /jffs/scripts/services-start)
				# delete existing comment line if it exists - cleanup any residual stuff
				if [ "$STARTUPLINECOUNT" -ne 0 ]; then
					sed -i -e '/'"$SCRIPT_NAME"'/d' /jffs/scripts/services-start
                    echo "/bin/sh ${SCRIPT_INSTALL_PATH} hide    # added by ${SCRIPT_NAME}" >> /jffs/scripts/services-start
                else
                    echo "/bin/sh ${SCRIPT_INSTALL_PATH} hide    # added by ${SCRIPT_NAME}" >> /jffs/scripts/services-start
				fi
			# a service-event file did not exist, so create one
            else
				echo "#!/bin/sh" > /jffs/scripts/services-start
				echo "" >> /jffs/scripts/services-start
				echo "/bin/sh ${SCRIPT_INSTALL_PATH} hide  # added by ${SCRIPT_DISPLAY_NAME}" >> /jffs/scripts/services-start
				chmod 0755 /jffs/scripts/services-start
			fi
        ;;
        'uninstall')
			Green "   - Removing ${SCRIPT_INSTALL_PATH} from services-start"
            # check if services-start line exists and if so, remove any HideUIMenus lines found
            if [ -f /jffs/scripts/services-start ]; then
				STARTUPLINECOUNT=$(grep -c "${SCRIPT_INSTALL_PATH}" /jffs/scripts/services-start)
				
				if [ "$STARTUPLINECOUNT" -gt 0 ]; then
					sed -i -e '/'"$SCRIPT_NAME"'/d' /jffs/scripts/services-start
				fi
			fi
        ;;
    esac
} # end of Auto_Start()


Setup_Aliases() {
    # Parameters: $1 - install or uninstall
    # shortcuts to launching script
    case $1 in
        'install')
            # remove shell alias
            local cmdline
            if [ -d /opt/bin ]; then
                # Entware is installed, so setup link to /opt/bin
                Green "   - Adding ${SCRIPT_NAME} link in Entware /opt/bin"
                ln -sf "${SCRIPT_INSTALL_PATH}" "/opt/bin/${SCRIPT_NAME}"
            else
                # Setup shell alias
                Green "   -  Adding ${SCRIPT_NAME} alias in profile.add"
                sed -i "/alias ${SCRIPT_NAME}/d" /jffs/configs/profile.add 2>/dev/null
                cmdline="alias ${SCRIPT_NAME}=\"sh ${SCRIPT_INSTALL_PATH}\" # ${SCRIPT_NAME} Addition"
                echo "${cmdline}" >> /jffs/configs/profile.add
            fi
        ;;
        'uninstall')
            # remove alias from profile.add. Brute force, meaning not checking to see if exists first, just assume and delete
            if [ -L /opt/bin/${SCRIPT_NAME} ]; then
                # Entware is installed, so setup link to /opt/bin
                Green "   - Deleting ${SCRIPT_NAME} link in Entware /opt/bin"
                rm "/opt/bin/${SCRIPT_NAME}"
            else
                # Remove alias from profile.add
                if [ -f /jffs/configs/profile.add ]; then
                    STARTUPLINECOUNT=$(grep -c '# '"$SCRIPT_NAME" /jffs/configs/profile.add)
                    if [ "$STARTUPLINECOUNT" -gt 0 ]; then
                        Green "   -  Deleting ${SCRIPT_NAME} alias in profile.add"
                        sed -i -e '/# '"$SCRIPT_NAME"'/d' /jffs/configs/profile.add
                    fi
                fi
            fi  
        ;;
    esac
} #  end of Setup_Aliases()

Custom_Settings(){
    # Parameters: $1 - install or uninstall
    # Add / delete a name space in the Asuswrt third party addons custome_settings.txt file
    case $1 in
        install)
            Green "   - Creating ${SCRIPTS_NAME_DISPLAY} cusotom_settings.txt name space"
            # check if any previous name space entries exist and remove them
			if [ -f $SETTINGS_FILE ]; then
				STARTUPLINECOUNT=$(grep -c "$SCRIPT_NAME_DISPLAY" $SETTINGS_FILE)
				# delete existing comment line if it exists - cleanup any residual stuff
				if [ "$STARTUPLINECOUNT" -gt 0 ]; then
					sed -i -e  '/'"$SCRIPT_NAME_DISPLAY"'/d' $SETTINGS_FILE
                    am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
				else
                    am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
				fi
			# a service-event file did not exist, so create one
            else
				am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
			fi
        ;; 
        uninstall)
            Green "   - Deleting ${SCRIPTS_NAME_DISPLAY} cusotom_settings.txt name space"
            # check if any previous name space entries exist and remove them
			if [ -f $SETTINGS_FILE ]; then
				STARTUPLINECOUNT=$(grep -c "$SCRIPT_NAME_DISPLAY" $SETTINGS_FILE)
				# delete existing comment line if it exists - cleanup any residual stuff
				if [ "$STARTUPLINECOUNT" -gt 0 ]; then
					sed -i -e  '/'"$SCRIPT_NAME_DISPLAY"'/d' $SETTINGS_FILE
				fi
            fi
        ;;
    esac
} # end of Custom_Settings

Install() {
    # Parameter options: None
    # Install script and download webui file
    # This is also called by the update process once a new script is downloaded by update() function
    clear
    Scriptinfo

    Green "Installing ${SCRIPT_NAME_DISPLAY}"
    if [ ! Check_Firmware ]; then
        Red "[ERROR] Addons are not supported in this routers firmware - script aborting!!!"
        Press_Enter
        rm -f "${0}" 2>/dev/null
        exit 5
    fi

    # Create the directory for this scripts addon files
    if [ ! -d "${SCRIPT_NAME_DIR}" ]; then
        Green "   - Creating $SCRIPT_NAME ADDON directory"
        mkdir -p "${SCRIPT_NAME_DIR}"
    fi

    # download HideUIMenus script
    Green "   - Downloading $(basename "${SCRIPT_INSTALL_PATH}")"
    Download_File "$(basename "${SCRIPT_INSTALL_PATH}")" "${SCRIPT_INSTALL_PATH}" #HideUIMenus script
    chmod 755 ${SCRIPT_INSTALL_PATH} # make script executable

    # download a sample hidemenuslist file
    Green "   - Downloading $(basename "${HIDEMENUS_FILE_PATH}")"
    Download_File "$(basename "${HIDEMENUS_FILE_PATH}")" "${HIDEMENUS_FILE_PATH}" #HideUIMenus list

    # Create a defaultmenus file, containing the list of valid menu names to choose from for hiding
    grep index: /www/require/modules/menuTree.js | cut -d ' ' -f2- | sed 's/[",]//g' | awk "${FILTER_MENUS_LIST}" > "${DEFAULTMENUS_FILE_PATH}"

    # add command line to /jffs/scripts/services-start to modify the router WebUI when router bootsup
    Add_Startup install

    # add alias command for invoking script
    Setup_Aliases install

    # create Asuswrt third party addon name space with version information
    Custom_Settings install

    # Install complete messages
    Green "${SCRIPT_NAME_DISPLAY} installation complete!"
    Magenta "   - be sure to run the hideuimenus command, then choose option 5 to edit which menus you want to hide, then option 6 to apply the changes"
} # end of Install()

Update() {

    # Check for, and optionally apply updates.
    # Parameter options: check (do not update), silent (update without prompting)
    local updatestatus yn remotever
    Scriptinfo
    Green "Checking for updates"
    # Update the webui status thorugh detect_update.js ajax call.
    # Get the version of the script on Github
    localver="$(grep "SCRIPT_VERSION=" $SCRIPT_INSTALL_PATH | grep -m1 -oE "$scriptVersRegExp")"
    remotever="$(curl -fsL --retry 4 --retry-delay 5 "$GIT_URL/$SCRIPT_NAME" | grep "SCRIPT_VERSION=" | grep -m1 -oE "$scriptVersRegExp")"
    # Compare local and remote versions to see how to proceed
    if [ "$localver" != "$remotever" ]; then
        # version upgrade
        updatestatus="Update"
    else
        updatestatus="NoUpdate"
    fi

    if [ "${1}" = "check" ]; then
        # Do not proceed with any updating if check function requested
        return
    fi

    if [ "${mode}" = "interactive" ] && [ -z "${1}" ]; then
        case "${updatestatus}" in
        'NoUpdate')
            Green "   - You have the latest version installed"
            printf " Would you like to overwrite your existing installation anyway? [y=Yes n=No]: "
            ;;
        'Update')
                    # New Version Number
            Green "   - ${SCRIPT_NAME_DISPLAY} v${updatestatus} is now available!"
            printf " Would you like to update now? [y=Yes n=No]: "
            ;;
        *)
            Red "   - Error occured checking version information"
            Press_Enter
            return
            ;;
        esac
        read -r yn
        printf "\n"
        if [ "${yn}" = "n" ] || [ "${yn}" = "N" ]; then
            Cyan "   - No Changes have been made"
            return 0
        fi
    fi
    Green "   - Installing latest version of ${SCRIPT_NAME_DISPLAY}"
    Download_File "$(basename "${SCRIPT_INSTALL_PATH}")" "${SCRIPT_INSTALL_PATH}"
    Install
    
    # Output completion message
    Green "Completed installing script updates"
} # end of Update()

Edit () {
    local before_hash 
    local after_hash 

    # Get the hash of the hidemenus list file BEFORE editing
    before_hash=$(sha256sum "/jffs/addons/modrouterui/hide_menus_list" | awk '{ print $1 }')

    nano "${HIDEMENUS_FILE_PATH}"

    # Get the hash of the hidemenus list file AFTER editing
    after_hash=$(sha256sum "/jffs/addons/modrouterui/hide_menus_list" | awk '{ print $1 }') 

    # Check for any changes
    if [ ! "${before_hash}" = "${after_hash}" ]; then
        Yellow "Your changes have been saved to $HIDEMENUS_FILE_PATH - to apply changes to the router UI, run the HIDE function"
    else
        Yellow "No changes were made to the $HIDEMENUS_FILE_PATH"
    fi
} # end of Edit()

Hide () {
    local count_menus_tohide
    local invalid_menus
    local final_menus_tohidelist
    final_menus_tohidelist="${SCRIPT_NAME_DIR}/menus_to_hide"

    # Determine where to show progress message
    if [ "${mode}" = "interactive" ]; then
        Green "Hideing menus noted in the hidemenus file"
    else
        Logmsg "[INFO] Hideing menus noted in the hidemenus file"
    fi

    # check to see if the hidenames file doesn't exist or is empty
    if [ ! -f "${HIDEMENUS_FILE_PATH}" ] || [ ! -s "${HIDEMENUS_FILE_PATH}" ] ; then
        if [ "${mode}" = "interactive" ]; then
            Red "${HIDEMENUS_FILE_PATH} file is missing or is empty. Choose the menu Edit option or manually create it first"
            Press_Enter
            return
        else
            Logmsg "[ERROR] hidemenus file is missing or empty"
            exit 
        fi
    fi

    # chect to make sure the hidemenus files contains some uncommented menus to hide
    count_menus_tohide=$(grep -v '^#' "${HIDEMENUS_FILE_PATH}" | grep 'menu_' | wc -l) 
    if [ $count_menus_tohide = 0 ]; then 
        if [ "${mode}" = "interactive" ]; then
            clear
            Red "[ERROR] "${HIDEMENUS_FILE_PATH}" doesn't contain any un-commented menus to hide - no changes made to router UI"
            echo $invalid_menus
            return
        else
            Logmsg "[ERROR] "${HIDEMENUS_FILE_PATH}" doesn't contain any un-commented menus to hide - no changes made to router UI"
            exit
        fi
    fi    

    # Create the actual menus file to hide, from the uncommented and non-blank links in the menulist file
    grep -v "^#\|^$" < ${HIDEMENUS_FILE_PATH} > $final_menus_tohidelist

    # check to make sure hidemenus file contains valid menu names to hide 
    invalid_menus=$(grep -Fxvf "${DEFAULTMENUS_FILE_PATH}" "${final_menus_tohidelist}")

    # check to make sure hidemenus file contains valid menu names to hide 
    if [ $invalid_menus ]; then
        if [ "${mode}" = "interactive" ]; then
            clear
            Red "[ERROR] "${HIDEMENUS_FILE_PATH}" contains the following invalid menu name(s) - choose the HELP option for valid menu names to use"
            echo $invalid_menus
            return
        else
            Logmsg "[ERROR] "${HIDEMENUS_FILE_PATH}" contains invalid menu name(s) - correct the file and rerun"
            exit
        fi
    fi

    # create addonwebui lockfile to prevent any other addons attempting to update menutree.js at same time
    FD=386
    eval exec "${FD}>${LOCK_FILE}"
    /usr/bin/flock -x "${FD}"

    # copy the defaul menutree.js to /tmp
    if [ ! -f /tmp/menuTree.js ]; then
        cp /www/require/modules/menuTree.js ${MENUTREE_FILE}
        mount -o bind ${MENUTREE_FILE} /www/require/modules/menuTree.js
    fi
    umount /www/require/modules/menuTree.js 2>/dev/null

    # delete any existing exclusing that might be in the menutree.js
    sed -i "/\/\/hidemenus/d" ${MENUTREE_FILE}

    # find the line number in menuTree.js for the string exclude: and add 3, to position for the start of whwere we want to insert hide menu names
    lineNum="$(grep -n "exclude:" "${MENUTREE_FILE}" | head -n 1 | cut -d: -f1)"
    lineNum=$((lineNum + 3))

    # add text to menutree.js to show the start of my menu exlcusions
    sed -i "${lineNum}i /* Begin my exclusions - //hidemenus */" ${MENUTREE_FILE}

    # move forward one line for the next line add
    lineNum=$((lineNum + 1))

    # process hidemenus file, skipping comments and blank lines, and for each menu name, add it to the menutree.js file to be excluded
    while read -r line; do
        sed -i "${lineNum}i retArray.push("\"${line}\"");   //hidemenus" ${MENUTREE_FILE}
        lineNum=$((lineNum + 1)) 
    done < $final_menus_tohidelist

    # add text to menutree.js to show the end of my menu exclusions
    sed -i "${lineNum}i /* End my exclusions - //hidemenus */" ${MENUTREE_FILE} 

    # remount the modified menutree.js and release the lock file
    mount -o bind ${MENUTREE_FILE} /www/require/modules/menuTree.js
    /usr/bin/flock -u "${FD}"
    
    # output completion message
    if [ "${mode}" = "interactive" ]; then
        Green "Completed removing the menus you selected in the hidemenus file"
    else
        Logmsg "[Success] Completed removing the menus selected in the hidemenus file"
        exit
    fi
} # end of Hide()

Unhide () {

    Green "Removing hidden menus and returning to the defaults"

    # get a count of the number of hidemenus lines found
    num_hidemenus="$(grep -c "hidemenus" /tmp/menuTree.js)"

    # If the menuTree.js contained menu lines with the string "hidemenus", then remove them
    if [ $num_hidemenus -ne 0 ]; then
        # create addonwebui lockfile to prevent any other addons attempting to update menutree.js at same time
        FD=386
        eval exec "${FD}>${LOCK_FILE}"
        /usr/bin/flock -x "${FD}"
        # unmount the router menut (menuTree.js)
        umount /www/require/modules/menuTree.js 2>/dev/null
        # delete all lines containing the string hidemenus
		sed -i "/\/\/hidemenus/d" ${MENUTREE_FILE}
        # check to see if the menuTree.js file in the /tmp directory is the same as the routers default
		if diff -q /tmp/menuTree.js /www/require/modules/menuTree.js >/dev/null 2>&1; then
			# menuTree.js files are equal, so remove the one from /tmp since it doesn't contain any other custom addon web pages
			rm /tmp/menuTree.js
		else
			# Still some modifications from another script so remount
			mount -o bind /tmp/menuTree.js /www/require/modules/menuTree.js
		fi
		/usr/bin/flock -u "${FD}"
    fi

    # output completion message
    Green "Completed returning Router menus to defaults"
} # end of Unhide()

Uninstall () {
    Green "Uninstalling the ${SCRIPT_DISPLAY_NAME} script"

    # Remove the scripts addon directory
    Green "   - removing the scripts addon directory"
    rm -r ${SCRIPT_NAME_DIR}

    # Remove the scripts alias, either under /opt/bin or in profiles.add
    Setup_Aliases uninstall

    # Remove the addons custom-settings.txt entry
    Custom_Settings uninstall

    # Remove the addons startup line in services-start
    Add_Startup uninstall

    # Unhide menus that were added to menuTree.js to be excluded
    Unhide

    # output completion message
    Green "Completed uninstalling the ${SCRIPT_DISPLAY_NAME} script"
} # end of Uninstall()

Main_Menu() {
    local yn
    [ "${mode}" = "interactive" ] || return
    clear
    sed -n '2,8p' "${0}"		# display banner
    Scriptinfo
    Cyan "  (1) About        explain functionality"
    Cyan "  (2) Help         information on how to use this script"
    Cyan "  (3) Install      install HideUIMenus files"
    Cyan "  (4) Update       check for script updates"
    Cyan "  (5) Edit         edit the hidemenus file to only contain the menu names (menu_xxxx) you want to hide"
    Cyan '  (6) Hide         run this if you changed the contents of "hidemenus" file and dont want to reboot'
    Cyan "  (7) Unhide       restore router UI to default menus"
    Cyan "  (8) Debug        enable verbose logging for troubleshooting"
    Cyan "  (9) Uninstall    completely remove HideUIMenus from the router"
    Cyan "  (e) Exit         exit without doing anything"
    printf "\nMake a selection: "
    read -r input
    case "${input}" in
        '1')
            clear
            About
        ;;
        '2')
            clear
            Show_Help
        ;;
        '3')
            Install
        ;;
        '4')
            Update
        ;;
        '5')
            Edit
        ;;
        '6')
            Hide
        ;;
        '7')
            Unhide
        ;;
        '8')
            Debug
        ;;
        '9')
            Uninstall
            Magenta "   - Thanks for using $SCRIPT_NAME_DISPLAY - Bye"
            cd
            exit
        ;;
        'e'|'E'|'exit')
            return
        ;;
        *)
            printf "\n"
            Red "[ERROR] $input is not a valid option!"
            printf "n"
            exit 5
        ;;
    esac
    Press_Enter
    Main_Menu		# stay in the menu loop until exit is chosen
} # end of Main_Menu()

###---###---###---###---###---###---###---###---###---###---###---###---###---###---###---###---###
##
## Script Mainline
##

# Detect if script is run from an SSH shell interactively or from the WebUI (unattended)
if tty >/dev/null 2>&1; then
    mode="interactive"
else
    mode="unattended"
fi

# verify only certain unattended commmands were passed into script, otherwise exit
if [  ${mode} = "interactive" ];  then
    :
elif [  ${mode} = "unattended" ]  && [ ! $1 == "hide" ]; then
    echo "wrong combo"
    exit
fi

# Make sure the version in custom_settings.txt matches the version of this script
if [ "$(am_settings_get "${SCRIPT_NAME_DISPLAY}"_ver)" != "${SCRIPT_VERSION}" ]; then
	am_settings_set "${SCRIPT_NAME_DISPLAY}"_ver "${SCRIPT_VERSION}"
fi

# Check and process the parameter passed when calling this script
case "$1" in
    'menu'|'')
        Main_Menu
    ;;
    'hide')
        Hide
    ;;
    'unhide')
        Unhide
    ;;
    'install')
        Install
    ;;
    'update')
        Update
    ;;
    'edit')
        Edit
    ;;
    'hide')
        Hide
    ;;
    'unhide')
        Unhide
    ;;
    'debug')
        Debug
    ;;
    'uninstall')
        Uninstall
    ;;
    *)
    if [ ! "${mode}" = "interactive" ]; then
        Logmsg "[ERROR] >> $1 << is an unknown parameter; script ended unexpectedly"
        exit 5
    else
        printf "\n"
        Red "[ERROR] >> $1 << is not a valid option!"
        printf "\n"
        exit 5
    fi
    ;;
esac
